# Generated by Django 3.2.8 on 2021-10-25 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodegenerator',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcodegenerator',
            name='is_restrict',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userextended',
            name='create_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qrcodegenerator',
            name='presence',
            field=models.ManyToManyField(blank=True, related_name='presence', to=settings.AUTH_USER_MODEL),
        ),
    ]
