# Generated by Django 3.2.8 on 2021-11-25 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20211025_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='agency',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyname'),
        ),
        migrations.CreateModel(
            name='InvitationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.SlugField(max_length=255, unique=True)),
                ('valid_until', models.DateTimeField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyname')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
