# Generated by Django 3.2.8 on 2021-11-25 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20211126_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationlink',
            old_name='created_by',
            new_name='invitee',
        ),
        migrations.AddField(
            model_name='userextended',
            name='connected_spv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spv', related_query_name='spv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userextended',
            name='is_upper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', related_query_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
