# Generated by Django 3.2.8 on 2021-12-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211201_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodegenerator',
            name='for_date',
        ),
        migrations.RemoveField(
            model_name='qrcodegenerator',
            name='is_restrict',
        ),
        migrations.RemoveField(
            model_name='qrcodegenerator',
            name='presence',
        ),
        migrations.AddField(
            model_name='qrcodegenerator',
            name='qr_img',
            field=models.FileField(blank=True, upload_to='qr/'),
        ),
        migrations.CreateModel(
            name='PresenceRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.qrcodegenerator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userextended')),
            ],
        ),
    ]
