# Generated by Django 3.2.8 on 2021-12-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211221_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='connected_spv',
        ),
        migrations.AlterField(
            model_name='userextended',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyname'),
        ),
    ]
