# Generated by Django 3.2.8 on 2021-12-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_qrcodegenerator_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencerecap',
            name='qr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_c', related_query_name='qr_c', to='dashboard.qrcodegenerator'),
        ),
    ]
